modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
    modId="havencobblegens"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    description='''${mod_description}'''
    logoFile="logo.png"
[[dependencies.havencobblegens]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.havencobblegens]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.havencobblegens]]
    modId="jei"
    versionRange="[19.19,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.havenksh]]
    modId="jade"
    versionRange="[11.7.0,)"
    ordering="NONE"
    side="BOTH"